### ISSUE TITLE
Clicking on "Copy Query" gives Gateway Timeout

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair-lsst-web#25]
This may be a short lived problem. I have tried 3 times to copy this Query:

https://lasair-iris.roe.ac.uk/query/203/

All received a Gateway Timeout. Will try again in 1 hr and report back.

**Comment by thespacedoctor** [comment]
I can confirm the problem persists 1 hr later so probably not a database locking issue/

**Comment by RoyWilliams** [comment]
It is because the query has active=2, meaning it puts out a kakfa stream. When such a query is modified, saved, or copied, its kafka topic and stream log are deleted, then the new query is run with LIMIT 10 and those results pushed into kafka and stream log. This is so that these collections of results synchronise with the query as it is now, not as it was then. Clearly something is busted in this complicated chain of events.

I'll try to figure out exactly what is wrong, see if I can use the public kafka system from the dev webserver. Then simplfy this complicated behaviour.

**Comment by thespacedoctor** [comment]
All fixed! Thanks Roy!!
